### ISSUE TITLE
realtime digital human

### ISSUE THREAD

**Issue by lipku** [DataExplorerUser/dpg_resources#3]
![demo](https://github.com/DataExplorerUser/dpg_resources/assets/5893340/fef8b420-bd07-4a5c-877d-5c3fca8e34f3)

**Comment by bandit-masked** [comment]
谢谢。视频的渲染非常令人印象深刻。然而，由于展示是关于使用 Dear PyGui 制作的应用程序，我希望除了令人印象深刻的实时数字人之外，还能更多地关注 GUI。该应用程序是否除了输入文本之外还有更多功能？例如，我可以想象在训练模型时的各种设置。

Thank you very much. The rendering of the video is very impressive. However, since the showcase is about applications made with Dear PyGui, I was hoping for more focus on the GUI in addition to the impressive real-time digital human. Is there more to the app than just input text? I can imagine all kinds of settings when training the model, for example.
